mikrotik_router:
  ip_address: '0.0.0.0'
  ssh_user: 'admin'
  ssh_pass: 'password'
  monitor_interface: 'bridge-local'
  remote_voip_server_ip: '0.0.0.0/32'   # Look for network traffic on the router with this destination
  voip_activity_threshold_kilobits: 20  # How many kilobits of traffic is required to consider that phone active

lifx:
  light:
    name: 'Phone Status Light'
    saturation: 1                 # Can be anything between 0 and 1
    brightness: 0.7               # Can be anything between 0 and 1
    kelvin: 3500                  # Can be anything between 2500 and 9000
  fade_duration: 0.5              # How long to fade in the color, in seconds
  periodically_refresh_delay: 60  # How often to update the bulb, in seconds, regardless of phone activity

number_of_phone_lines: 20 # This number will be used to divide up the color spectrum and randomly assign colors to phones

# To ignore specific VoIP network phones, simply add their IP address to the list below
# Any network traffic from these IP addresses will not trigger the light:
phone_ip_addresses_to_ignore:
  - '0.0.0.0'          # Example IP - Can be deleted/replaced
  - '255.255.255.255'  # Example IP - Can be deleted/replaced

triggers:
  lines_active:
    enabled: false
    system_command: '/usr/bin/say phone lines are active' # The command that is executed when one or more lines become active
  lines_clear:
    enabled: false
    system_command: '/usr/bin/say phone lines are clear' # The command that is executed when all the lines are hung up